### ISSUE TITLE
A lot of folders!

### ISSUE THREAD

**Issue by ghost** [WebAhead7/Pokesour#13]
In my opinion there is no need to put each component's js and css file in separate folder. 
Just put them all in the same folder ( components folder).
import comp from './component/comp/comp'; <-- bad
import comp from './component/comp;      <-- good

**Comment by alaabashiyi** [comment]
components should belong to it's files so each component and style and maybe helpers should be in the same folder. now to fix the import Component from '../component/component' i could name the component name 'index.jsx', and that fixes the import, other than that, imagine you have a 60 components with their styles. in one folder? i would call that
KHABESA

**Comment by ghost** [comment]
Yep you are right in case it is a really big project.
