### ISSUE TITLE
bad practice with async await

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/Pokesour#9]
https://github.com/WebAhead7/Pokesour/blob/main/src/screens/Profile/Profile.js#L13-L17

an `await` statement should **always** be wrapped around `try catch`, because if it throws an error right now it will crash your website

**Comment by Karyum** [comment]
you also need to handle errors here
https://github.com/WebAhead7/Pokesour/blob/main/src/screens/App/App.jsx#L19

**Comment by alaabashiyi** [comment]
i bad, i forgot the try, catch.
added.
